update-check:
  # Whether to automatically check updates on server startup.
  # You can then use /updates show without running /updates check.
  on-startup: false

  # How many threads to use for update checking.
  threads: 4

  # Release channels to consider.
  # You can for example ignore beta and alpha releases.
  consider-channels:
    - release
    - beta
    - alpha

command:
  action-bar:
    # Whether to show an action bar with current progress,
    # to the player that run the check command.
    enable: true
    # Interval in ticks
    interval: 1

  # How many projects to show on one page of
  # /updates show <plugins | datapacks>.
  page-size: 10

  # How many minutes after an update check,
  # running command again will show a warning.
  confirm-duration: 10